services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: churn-api-service
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: churn-streamlit-service
    command: [ "streamlit", "run", "app/streamlit_app.py", "--server.port=8501", "--server.address=0.0.0.0" ]
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://api:8000
    depends_on:
      - api
    restart: always
